### ISSUE TITLE
featureRequest - command aliases

### ISSUE THREAD

**Issue by 7yultukuri7** [mouse484/Ecstar#15]
コマンドのエイリアス
```
module.exports = class extends command {
    constructor(client) {
        super(client, {
		name: 'help',
		aliases: ['tasukete', '助けて', 'ヘルプ'],
        });
    }
    run(message) {
              //...
    }
};
```

**Comment by mouse484** [comment]
実装予定ですが
コマンドの処理部分の仕組み的に現状は難しいので後回しになっています
~~メイン垢消されて大きく気力無くなってしまったのもありますが~~

**Comment by acrylic-style** [comment]
~~[あれ？Commandクラスってどこかで見たような。。。](https://github.com/acrylic-style/bot-framework/blob/master/src/structures/Command.js)~~

**Comment by mouse484** [comment]
https://github.com/mouse484/Ecstar/commit/c8a971ade8046a5841a89da0df59e1dbd6926d45
